### ISSUE TITLE
Pinned versions of packages cause installation problems, download script does not work

### ISSUE THREAD

**Issue by jin-eld** [licksylick/AutoTrackAnything#1]
Здорова!

thank you for the project!
I am wondering why it was necessary to pin some packages to specific versions? On Fedora 38 it lead to an installation error due to incompatible dependency versions. I relaxed the version requirements like below and was then able to install and run everything just fine on my ROCm setup:

```
diff --git a/requirements.txt b/requirements.txt
index d9fd103..6ef930c 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,9 +1,9 @@
 mega.py
 mobile-sam @ git+https://github.com/ChaoningZhang/MobileSAM.git
-numpy==1.23.1
+numpy>=1.23.1
 opencv-python>=4.1.1
-pandas==1.4.3
+pandas>=1.4.3
 Pillow>=7.1.2
 scikit-image==0.19.3
-timm==0.9.12
-ultralytics
\ No newline at end of file
+timm>=0.9.12
+ultralytics
```

The next issue I had was with the download script, the "mega" module does not seem to work on my Python version:
```
Traceback (most recent call last):
  File "/mnt/ssd/xxx/AutoTrackAnything/download_models.py", line 1, in <module>
    from mega import Mega
  File "/home/xxx/.local/lib/python3.11/site-packages/mega/__init__.py", line 1, in <module>
    from .mega import Mega  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xxx/.local/lib/python3.11/site-packages/mega/mega.py", line 18, in <module>
    from tenacity import retry, wait_exponential, retry_if_exception_type
  File "/home/xxx/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 451, in <module>
    from tenacity._asyncio import AsyncRetrying
  File "/home/xxx/.local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 33, in <module>
    class AsyncRetrying(BaseRetrying):
  File "/home/xxx/.local/lib/python3.11/site-packages/tenacity/_asyncio.py", line 41, in AsyncRetrying
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'. Did you mean: 'coroutines'?
```

I downloaded and unzipped the models zip manually, which worked. Still, I was wondering - why mega.nz, why not just use the one from the mobile sam repo?
https://github.com/ChaoningZhang/MobileSAM/blob/master/weights/mobile_sam.pt

I think XMem.pth should also be available from the original authors.

Other than that - really nice, it worked well on a video containing a person.

Do you have any hints on how to use it to track specific animals? Would it be enough to change the keypoint keywords or is there more to it?

**Comment by licksylick** [comment]
Hello, @jin-eld! Thanks for your interest in the project.
Indeed, the module 'mega' may not work correctly on some versions of Python. I will fix it
  
> Other than that - really nice, it worked well on a video containing a person.
> Do you have any hints on how to use it to track specific animals? Would it be enough to change the keypoint keywords or is there more to it?
  
Sure, if you want to track animals, all you need is just to replace model (check the file pose-estimation.py). You should return list of bboxes of animals from model predictions in 'get_filtered_bboxes_by_confidence' method. 

Important that you return the boxes only of those animals that are clearly visible in the frame (for people, I used the confidence of the model at keypoints). Good luck!
