### ISSUE TITLE
[Question] bbox to mobile sam

### ISSUE THREAD

**Issue by sam-ulrich1** [licksylick/AutoTrackAnything#2]
If I understand the project correctly the use of yolo to create bbox and then prompt sam with the bbox is similar in principle to mobilesamv2 correct?

Just trying to make sure my underlying assumptions are correct here

**Comment by licksylick** [comment]
Hello! Thank you for your interest in AutoTrackAnything.
You are correct, but also I create and merge masks from SAM and use it in XMEM algorithm for tracking.
Now it's pipeline for person tracking (It's not necessary, but I use keypoints and their confidences to make sure that each new person is clearly visible in the frame), but you can easy use it for track everything you want - all you need is bboxes from yolo (change yolo model on yours and remove filtering by keypoints).

**Comment by sam-ulrich1** [comment]
Awesome! Thanks for confirming that! I've been digging into it. Unfortunately, Xmem looks to have hard time with tracking a large quantity of objects so I may need to use a non-temporal VOS algorithm
