### ISSUE TITLE
How does ReID work in your project?

### ISSUE THREAD

**Issue by RunsenXu** [licksylick/AutoTrackAnything#3]
Hi,

Thank you for this great project! I wonder how did your project handle ReID, i.e., re-tracking the object out of frame? Can it handle re-tracking an object being out of frame for a long time?

**Comment by HAFDIAHMED** [comment]
> Hi,
> 
> Thank you for this great project! I wonder how did your project handle ReID, i.e., re-tracking the object out of frame? Can it handle re-tracking an object being out of frame for a long time?
I have the same question

**Comment by HAFDIAHMED** [comment]
Up

**Comment by licksylick** [comment]
Hello! Thank you for your interest in AutoTrackAnything.
Each situation is unique, so I cannot guarantee performance in all cases. In my case, an object could disappear from the frame for up to a minute, but then was correctly re-identified. I think you need to check this out for yourself. 
Also you can check original article https://arxiv.org/pdf/2207.07115
